SET IDENTITY_INSERT Genres ON;
INSERT INTO Genres (Id, Name) VALUES (1, N'Animation');
INSERT INTO Genres (Id, Name) VALUES (2, N'Family');
INSERT INTO Genres (Id, Name) VALUES (3, N'Fantasy');
INSERT INTO Genres (Id, Name) VALUES (4, N'Adventure');
INSERT INTO Genres (Id, Name) VALUES (5, N'Music');
INSERT INTO Genres (Id, Name) VALUES (6, N'Horror');
INSERT INTO Genres (Id, Name) VALUES (7, N'Science Fiction');
INSERT INTO Genres (Id, Name) VALUES (8, N'Mystery');
INSERT INTO Genres (Id, Name) VALUES (9, N'Thriller');
INSERT INTO Genres (Id, Name) VALUES (10, N'Drama');
INSERT INTO Genres (Id, Name) VALUES (11, N'Action');
INSERT INTO Genres (Id, Name) VALUES (12, N'Crime');
INSERT INTO Genres (Id, Name) VALUES (13, N'Romance');
INSERT INTO Genres (Id, Name) VALUES (14, N'Comedy');
INSERT INTO Genres (Id, Name) VALUES (15, N'History');
INSERT INTO Genres (Id, Name) VALUES (16, N'War');
INSERT INTO Genres (Id, Name)VALUES (17, N'Western');
SET IDENTITY_INSERT Genres OFF;
